### ISSUE TITLE
ReleaseDLL x64 compile failure

### ISSUE THREAD

**Issue by BrisingrAerowing** [ShiftMediaProject/nettle#2]
## Context

When trying to compile with VS2017 (with YASM installed), it fails finding the compiled ASM files.

## Expected Behavior

The build completes

## Actual Behavior

I get an error stating 'cannot open input file '&lt;path-to-obj-dir&gt;\aes-decrypt-internal-2.obj'. Checking that path shows no .obj files for the ASM files.

GMP build perfectly fine with the same setup, so I'm not sure what got borked.

## Steps to Reproduce

1.  Visual Studio 2017 Community
2.  Try to compile nettle after having built GMP
3.  Compilation errors out
4.  

## Your Environment

* Version Used: Master Branch (3.4.1 merge)
* Operating System and Version: Windows 10 x64
* Compiler and Version(s): Visual Studio 2017 Community / YASM 1.3.0 (vsyasm)

**Comment by BrisingrAerowing** [comment]
I found the issue. The ASM files output is set to $(Intdir), where it needs to have %(Filename).obj at the end to specify the actual file.

**Comment by Sibras** [comment]
This can sometimes occur due to an installation problem. Not sure why but a reinstall usually fixes it.
The ASM output of $(Intdir) should automatically expand to create an object file in that folder with a name of %(Filename). But for some reason VS and yasm dont always talk to each other correctly. I havnt run into this issue myself and the build bots always work fine. But i have heard a few others who have had similar issues.

**Comment by BrisingrAerowing** [comment]
Weird.
